apiVersion: v1
appVersion: "0.0.3"
description: Helm chart for deploying a custom certificate issuer controller. The certificate issuer controller is a [cert-manager](https://cert-manager.io/docs/) resource managing certificate requests in a private PKI.
name: dvpe-certificate-issuer-controller
version: 0.0.3
home: https://github.com/dvpe-cloud/dvpe-helm
keywords:
  - automation
  - gitops
  - issuer-controller
maintainers:
  - name: mithie
  - name: herrLierb
  - name: christodo
