# Values for issuer-controller

# -------------------------------#
# values.yaml value section      #
# -------------------------------#
issuercontroller:
  plane:
    # issuercontroller.plane.name -- Name of the Controller Plane
    name: wadtfy-cert-issuer-controller-system
  spec:
    # issuercontroller.spec.image -- Name of issuer-controller deployment image
    image:
      # issuercontroller.spec.image.repository -- The docker repository to pull the service image from.
      repository:
      # issuercontroller.spec.image.name -- The image name to use.
      name: wadtfy-issuer
      # issuercontroller.spec.image.tag -- The image version to use.
      tag: 1.2.0
      # issuercontroller.spec.image.pullPolicy -- The default rule for downloading images.
      pullPolicy: IfNotPresent
  externalsecrets:
    # issuercontroller.externalsecrets.name -- The name of the external secret key containing the docker credentials for this deployment
    name:
