{{- $serviceName := include "service.name" . -}}
{{- with .Values.autoscaling }}
{{- if .enabled }}
{{- if or .metrics.resource.cpu.targetAverageUtilization .metrics.resource.memory.targetAverageUtilization }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $serviceName }}
spec:
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $serviceName }}
  metrics:
    {{- /*
      Order of metrics is important: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/, https://github.com/kubernetes/kubernetes/issues/74099
    */}}
    {{- if .metrics.resource.memory.targetAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .metrics.resource.memory.targetAverageUtilization }}
    {{- end }}
    {{- if .metrics.resource.cpu.targetAverageUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .metrics.resource.cpu.targetAverageUtilization }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
