{{- $serviceName := include "service.name" . -}}
{{- $upstreamName := include "upstream.name" . -}}

{{- if .Values.gloo.enabled }}

apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: {{ $upstreamName }}
  namespace: {{ .Values.gloo.upstream.namespace }}
  {{- if .Values.gloo.fds.enabled }}
  labels:
    discovery.solo.io/function_discovery: enabled
  {{- end }}
spec:
  kube:
    selector:
      app: {{ $serviceName }}
    serviceName: {{ $serviceName }}-svc
    serviceNamespace: {{ .Release.Namespace }}
    servicePort: {{ .Values.service.spec.ports.https.port }}
    {{- if .Values.gloo.fds.enabled }}
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://{{ $serviceName }}-svc.{{ .Release.Namespace }}:{{ .Values.service.spec.ports.https.port }}{{ .Values.gloo.fds.path }}
    {{- end }}
  sslConfig:
    alpnProtocols:
      - istio
    sds:
      certificatesSecretName: istio_server_cert
      clusterName: gateway_proxy_sds
      targetUri: 127.0.0.1:8234
      validationContextName: istio_validation_context

{{- end }}
