{{- $serviceName := include "service.name" . -}}

  {{- if .Values.gloo.enabled }}

apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: {{ $serviceName}}-{{ .Values.gloo.authConfig.name }}
  namespace: {{default .Release.Namespace .Values.gloo.authConfig.namespace }}
spec:
  configs:
    {{- if .Values.gloo.authConfig.spec.configs.oauth.enabled }}
    - oauth:
        app_url: "https://{{ .Values.gloo.virtualservice.spec.virtualHost.domains }}"
        callback_path: {{ .Values.gloo.virtualservice.spec.virtualHost.routes.callbackUrlPath }}
        client_id: {{ .Values.gloo.authConfig.spec.configs.oauth.client_id }}
        client_secret_ref:
          {{- if .Values.externalSecrets.oidc.key }}
          name: {{ $serviceName }}-oidc-secrets
          namespace: {{ .Release.Namespace }}
          {{- else }}
          name: {{ .Values.gloo.authConfig.spec.configs.oauth.client_secret_ref.name }}
          namespace: {{default .Release.Namespace .Values.gloo.authConfig.spec.configs.oauth.client_secret_ref.namespace }}
          {{- end }}
        issuer_url: {{ .Values.gloo.authConfig.spec.configs.oauth.issuer_url }}
        scopes:
        {{- if .Values.gloo.authConfig.spec.configs.oauth.scopes }}
        {{- toYaml .Values.gloo.authConfig.spec.configs.oauth.scopes | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.gloo.authConfig.spec.configs.backendPlugin.enabled }}
    - pluginAuth:
        name: {{ .Values.gloo.authConfig.spec.configs.backendPlugin.name }}
        pluginFileName: {{ .Values.gloo.authConfig.spec.configs.backendPlugin.name }}.so
        exportedSymbolName: Plugin
        config:
          CacheTableName: {{ .Values.gloo.authConfig.spec.configs.backendPlugin.config.cacheTableName }}
          AwsRegion:  {{ .Values.gloo.authConfig.spec.configs.backendPlugin.config.awsRegion }}
          OidcUrl: {{ .Values.gloo.authConfig.spec.configs.backendPlugin.config.oidcUrl }}
          JwksUrl: {{ .Values.gloo.authConfig.spec.configs.backendPlugin.config.jwksUrl }}
    {{- end }}
    {{- if .Values.gloo.authConfig.spec.configs.m2mPlugin.enabled }}
    - pluginAuth:
        name: {{ .Values.gloo.authConfig.spec.configs.m2mPlugin.name }}
        pluginFileName: {{ .Values.gloo.authConfig.spec.configs.m2mPlugin.name }}.so
        exportedSymbolName: Plugin
        config:
          CacheTableName: {{ .Values.gloo.authConfig.spec.configs.m2mPlugin.config.cacheTableName }}
          AwsRegion:  {{ .Values.gloo.authConfig.spec.configs.m2mPlugin.config.awsRegion }}
          OidcUrl: {{ .Values.gloo.authConfig.spec.configs.m2mPlugin.config.oidcUrl }}
          OidcClientId: {{ .Values.gloo.authConfig.spec.configs.m2mPlugin.config.clientId }}
          OidcClientSecret: {{ .Values.gloo.authConfig.spec.configs.m2mPlugin.config.clientSecret }}
      {{- end }}
      {{- if .Values.gloo.authConfig.spec.configs.additionalPlugins }}
    {{- toYaml .Values.gloo.authConfig.spec.configs.additionalPlugins | nindent 4 }}
  {{- end }}
  {{- end }}
