{{- $serviceName := include "service.name" . -}}
{{- $upstreamName := include "upstream.name" . -}}

{{- if .Values.gloo.enabled }}

apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: {{ $upstreamName }}
  namespace: {{ .Values.gloo.upstream.namespace }}
  {{- if .Values.gloo.upstream.fds }}
  labels:
    discovery.solo.io/function_discovery: enabled
  {{- end }}
spec:
  kube:
    selector:
      app: {{ $serviceName }}
    serviceName: {{ $serviceName }}-svc
    serviceNamespace: {{ .Release.Namespace }}
    servicePort: {{or .Values.service.spec.ports.https.port .Values.service.spec.ports.http.port}}
  {{- if .Values.istio.enabled }}
  sslConfig:
    alpnProtocols:
      - istio
    sds:
      certificatesSecretName: istio_server_cert
      clusterName: gateway_proxy_sds
      targetUri: 127.0.0.1:8234
      validationContextName: istio_validation_context

  {{- end }}
{{- end}}
