{{- $upstreamName := include "upstream.name" . -}}
{{- $serviceName := include "service.name" . -}}

{{- if .Values.gloo.enabled }}

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: {{ $serviceName }}-virtualservice
  namespace: {{ .Release.Namespace }}
spec:
  sslConfig:
    secretRef:
      name: {{ .Values.gloo.virtualservice.spec.sslConfig.secretRef.name }}
      namespace: {{default .Values.gloo.namespace .Values.gloo.virtualservice.spec.sslConfig.secretRef.namespace }}
  virtualHost:
    domains:
      - {{ .Values.gloo.virtualservice.spec.virtualHost.domains }}
    {{- if .Values.gloo.virtualservice.spec.virtualHost.cors.allowOrigin }}
    options:
      cors:
        allowCredentials: true
        allowHeaders:
          {{- range .Values.gloo.virtualservice.spec.virtualHost.cors.allowHeaders }}
          - {{ . }}
          {{- end }}
        allowMethods:
          {{- range .Values.gloo.virtualservice.spec.virtualHost.cors.allowMethods }}
          - {{ . }}
          {{- end }}
        allowOrigin:
          {{- range .Values.gloo.virtualservice.spec.virtualHost.cors.allowOrigin }}
          - {{ . | quote }}
          {{- end }}
        allowOriginRegex:
        exposeHeaders:
          {{- range .Values.gloo.virtualservice.spec.virtualHost.cors.exposeHeaders }}
          - {{ . }}
          {{- end }}
        maxAge: {{ .Values.gloo.virtualservice.spec.virtualHost.cors.maxAge }}
    {{- end }}
    routes:
      {{- if .Values.gloo.virtualservice.spec.virtualHost.routes.swagger.rewriteUrl }}
      - matchers:
          - prefix: {{ .Values.gloo.virtualservice.spec.virtualHost.routes.swagger.rewriteUrl }}
        routeAction:
          single:
            upstream:
              name: {{ $upstreamName }}
              namespace: {{ .Values.gloo.upstream.namespace }}
        options:
          prefixRewrite: {{ .Values.gloo.virtualservice.spec.virtualHost.routes.swagger.path }}
      {{- end }}
      {{- if .Values.gloo.virtualservice.spec.virtualHost.routes.callbackUrlPath }}
      - matchers:
          - prefix: {{ .Values.gloo.virtualservice.spec.virtualHost.routes.callbackUrlPath }}
        routeAction:
          single:
            upstream:
              name: {{ $upstreamName }}
              namespace: {{ .Values.gloo.upstream.namespace }}
        options:
          extauth:
            configRef:
              name: {{ $serviceName}}-{{ .Values.gloo.authConfig.name }}
              namespace: {{default .Release.Namespace .Values.gloo.authConfig.namespace }}
      {{- end }}
      {{- if .Values.gloo.virtualservice.spec.virtualHost.routes.appPath }}
      - matchers:
          - prefix: {{ .Values.gloo.virtualservice.spec.virtualHost.routes.appPath }}
        routeAction:
          single:
            upstream:
              name: {{ $upstreamName }}
              namespace: {{ .Values.gloo.upstream.namespace }}
        options:
          extauth:
            configRef:
              name: {{ $serviceName}}-{{ .Values.gloo.authConfig.name }}
              namespace: {{default .Release.Namespace .Values.gloo.authConfig.namespace }}
      {{- end}}
      {{- if ne .Values.gloo.virtualservice.spec.virtualHost.routes.appPath "/" }}
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: {{ $upstreamName }}
              namespace: {{ .Values.gloo.upstream.namespace }}
      {{- end}}
      {{- if .Values.gloo.virtualservice.spec.virtualHost.routes.additionalRoutes }}
    {{- toYaml .Values.gloo.virtualservice.spec.virtualHost.routes.additionalRoutes | nindent 6 }}
      {{- end }}
{{- end }}
