{{- $serviceName := include "service.name" . -}}
{{- with .Values.externalSecrets }}

{{- if or .service.key .service.keys }}
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-service-secrets
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store-{{ $.Release.Namespace }}
  target:
    name: {{ $serviceName }}-service-secrets
  dataFrom:
  {{- if .service.key }}
  - extract:
      key: {{ .service.key }}
  {{- end }}
  {{- range .service.keys }}
  - extract:
      key: {{ . }}
  {{- end }}
  refreshInterval: {{ .service.refreshInterval }}
{{- end }}

{{- if and .oauth2.key $.Values.gloo.authConfig.spec.configs.oauth.clientId }}
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-oidc-secrets
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store-{{ $.Release.Namespace }}
  target:
    name: {{ $serviceName }}-oidc-secrets
    template:
      metadata:
        annotations:
          resource_kind: '*v1.Secret'
  data:
    - secretKey: oauth
      remoteRef:
        key: {{ .oauth2.key }}
        property: {{ $.Values.gloo.authConfig.spec.configs.oauth.clientId | quote }}
  refreshInterval: {{ .oauth2.refreshInterval }}
{{- end }}

{{- if and .oauth2.key $.Values.gloo.authConfig.spec.configs.clientCredentialsPlugin.config.clientId }}
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-oauth2-client-credentials-secrets
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store-{{ $.Release.Namespace }}
  target:
    name: {{ $serviceName }}-oauth2-client-credentials-secrets
  data:
    - secretKey: ClientCredentialsFlow
      remoteRef:
        key: {{ .oauth2.key }}
        property: {{ $.Values.gloo.authConfig.spec.configs.clientCredentialsPlugin.config.clientId | quote }}
  refreshInterval: {{ .oauth2.refreshInterval }}
{{- end }}
{{- end }}
