{{- $serviceName := include "service.name" . -}}

{{- if .Values.externalSecrets.service.key }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.externalSecrets.service.key }}
{{- end }}

{{- if and .Values.externalSecrets.oauth2.key .Values.gloo.authConfig.spec.configs.oauth.client_id }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-oidc-secrets
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  template:
    metadata:
      annotations:
        resource_kind: '*v1.Secret'
  data:
    - key: {{ .Values.externalSecrets.oauth2.key }}
      property: {{ .Values.gloo.authConfig.spec.configs.oauth.client_id | quote }}
      name: oauth

{{- end }}

{{- if and .Values.externalSecrets.oauth2.key .Values.gloo.authConfig.spec.configs.clientCredentialsPlugin.config.clientId }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-oauth2-clientCredentials-secrets
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  template:
    metadata:
      annotations:
        resource_kind: '*v1.Secret'
  data:
    - key: {{ .Values.externalSecrets.oauth2.key }}
      property: {{ .Values.gloo.authConfig.spec.configs.clientCredentialsPlugin.config.clientId | quote }}
      name: ClientCredentialsFlow

{{- end }}

{{- if .Values.additionalparameters.secretsApplied }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-additional-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.additionalparameters.secrets }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
{{- end }}
