{{- $serviceName := include "service.name" . -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.spec.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.spec.ports.http.port }}
      targetPort: {{ .Values.service.spec.ports.http.targetPort }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.spec.ports.https.port }}
      targetPort: {{ .Values.service.spec.ports.https.targetPort }}
  selector:
    app: {{ $serviceName }}
