{{- $serviceName := include "service.name" . -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.spec.type }}
  ports:
    {{- if .Values.service.spec.ports.http.port }}
    - name: {{ .Values.service.spec.ports.http.name }}
      protocol: {{ .Values.service.spec.ports.http.protocol }}
      port: {{ .Values.service.spec.ports.http.port }}
      targetPort: {{ .Values.service.spec.ports.http.targetPort }}
    {{- end }}
    {{- if .Values.service.spec.ports.https.port }}
    - name: {{ .Values.service.spec.ports.https.name }}
      protocol: {{ .Values.service.spec.ports.https.protocol }}
      port: {{ .Values.service.spec.ports.https.port }}
      targetPort: {{ .Values.service.spec.ports.https.targetPort }}
    {{- end }}
  selector:
    app: {{ $serviceName }}
