{{- if .Values.gloo.enabled }}

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.gloo.virtualservice.name }}
  namespace: {{ .Release.Namespace }}
spec:
  sslConfig:
    secretRef:
      name: {{ .Values.gloo.virtualservice.spec.sslConfig.secretRef.name }}
      namespace: {{ .Values.gloo.virtualservice.spec.sslConfig.secretRef.namespace }}
  virtualHost:
    domains:
      {{- range .Values.gloo.virtualservice.spec.virtualHost.domains }}
      - {{ . | quote }}
      {{- end }}
    routes:
      - matchers:
        - prefix: {{ .Values.gloo.virtualservice.spec.virtualHost.routes.callbackUrlPath }}
        routeAction:
          single:
            upstream:
              name: {{ .Values.gloo.virtualservice.spec.virtualHost.routes.upstream.name }}
              namespace: {{ .Release.Namespace }}
    {{- if .Values.gloo.virtualservice.spec.virtualHost.routes.additionalRoutes }}
      {{- toYaml .Values.gloo.virtualservice.spec.virtualHost.routes.additionalRoutes | nindent 6 }}
    {{- end }}
    options:
      extauth:
        configRef:
          name: {{ .Values.gloo.authConfig.name }}
          namespace: {{ .Values.gloo.authConfig.namespace }}
{{- end }}
