{{- range $issuerName, $issuerParams := .Values.issuers }}
---

apiVersion: controller-manager.dvpe-cloud.github.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: wadtfy-{{ $issuerName }}-cluster-issuer
spec:
  certificateDetails:
    caInstance: {{ $issuerParams.caInstance }}
    ciID: {{ $issuerParams.ciID }}
    ciType: {{ $issuerParams.ciType }}
    certificateDataCAType: {{ $issuerParams.certificateDateCAType }}
    client: {{ $issuerParams.ciClient }}
    contactEmail: {{ $issuerParams.ciContactEmail }}
    requester: {{ $issuerParams.ciRequester }}
  clcm:
    credentialsSecret: wadtfy-{{ $issuerName }}-cluster-issuer-secret
    clcmHost: {{ $.Values.clcm.host }}
    clcmPort: {{ $.Values.clcm.port }}
    healthCheckTimeoutInSeconds: {{ $.Values.clcm.healthCheckTimeoutInSeconds }}

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wadtfy-{{ $issuerName }}-cluster-issuer-secret
  namespace: {{ $.Values.clcm.secretsNamespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: wadtfy-cluster-secret-store
  target:
    name: {{ $issuerParams.secretsManagerSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "{{ $issuerParams.secretsManagerSecretName }}"

---
{{- end }}
