{{- $clcm := .Values.clcm }}
{{- include "cluster-issuer" (list $clcm "wadtfy-internet-cluster-issuer" .Values.internet) }}
{{- include "cluster-issuer" (list $clcm "wadtfy-intranet-cluster-issuer" .Values.intranet) }}

{{- define "cluster-issuer" }}
{{- $clcm := index . 0 }}
{{- $name := index . 1 }}
{{- $cert := index . 2 }}
---
apiVersion: controller-manager.dvpe-cloud.github.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ $name }}
spec:
  certificateDetails:
    caInstance: {{ $cert.caInstance }}
    ciID: {{ $cert.ciID }}
    ciType: {{ $cert.ciType }}
    certificateDataCAType: {{ $cert.certificateDateCAType }}
    client: {{ $cert.ciClient }}
    contactEmail: {{ $cert.ciContactEmail }}
    requester: {{ $cert.ciRequester }}
  clcm:
    credentialsSecret: wadtfy-cluster-issuer-secret
    clcmHost: {{ $clcm.host }}
    clcmPort: {{ $clcm.port }}
    healthCheckTimeoutInSeconds: {{ $clcm.healthCheckTimeoutInSeconds }}
{{- end }}
