# Needs to be done in order to make .Values...work in range (limitation of go-templating (https://github.com/helm/helm/issues/1311)
{{- $root := . -}}


# Create for each entry in Issuers a ClusterIssuer and a Secret containing the
{{- range $issuerName, $issuerParams := .Values.issuers}}
apiVersion: controller-manager.dvpe-cloud.github.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: wadtfy-cluster-issuer-{{ $issuerName }}
spec:
  certificateDetails:
    caInstance: {{ $issuerParams.caInstance }}
    ciID: {{ $issuerParams.ciID }}
    ciType: {{ $issuerParams.ciType }}
    certificateDataCAType: {{ $issuerParams.certificateDateCAType }}
    client: {{ $issuerParams.ciClient }}
    contactEmail: {{ $issuerParams.ciContactEmail }}
    requester: {{ $issuerParams.ciRequester }}
  clcm:
    credentialsSecret: wadtfy-cluster-issuer-{{ $issuerName }}-secret
    clcmHost: {{ $root.Values.clcm.host }}
    clcmPort: {{ $root.Values.clcm.port }}
    healthCheckTimeoutInSeconds: {{ $root.Values.clcm.healthCheckTimeoutInSeconds }}

---

apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: wadtfy-cluster-issuer-{{ $issuerName }}-secret
  namespace: {{ $root.Values.clcm.secretsNamespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ $issuerParams.secretsmanagerSecretName }}
{{- end}}
