{{- $clcm := .Values.clcm }}
{{- range .Values.clusterIssuers }}
---
apiVersion: controller-manager.dvpe-cloud.github.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  certificateDetails:
    caInstance: {{ .caInstance }}
    ciID: {{ .ciID }}
    ciType: {{ .ciType }}
    certificateDataCAType: {{ .certificateDateCAType }}
    client: {{ .ciClient }}
    contactEmail: {{ .ciContactEmail }}
    requester: {{ .ciRequester }}
  clcm:
    credentialsSecret: wadtfy-cluster-issuer-secret
    {{- if $clcm.host  }}
    clcmHost: {{ $clcm.host -}}
    {{- end -}}
    {{ if $clcm.port }}
    clcmPort: {{ $clcm.port }}
    {{- end -}}
    {{ if $clcm.healthCheckTimeoutInSeconds   }}
    healthCheckTimeoutInSeconds: {{ $clcm.healthCheckTimeoutInSeconds }}
    {{- end -}}
{{- end }}
