apiVersion: v2
appVersion: "1.1"
description: "Helm Chart for installing a Custom Crossplane API, allowing to create an EFS Filesystem."
name: crossplane-efs
version: 0.4.0
home: https://github.com/dvpe-cloud/dvpe-helm
keywords:
  - dvpe-helm
  - automation
  - gitops
  - crossplane
maintainers:
  - name: mithie
  - name: herrLierb
