aws:
  # aws.accountId -- ID of the AWS Account this component should be provisioned to.
  accountId:

xrd:
  # xrd.apiGroup -- The name of the API Group this resource should be exposed to.
  apiGroup:
  # xrd.version -- The version of this component (MUST not be overridden from outside).
  version:

composition:
  # composition.name -- The name of the crossplane composition (MUST not be overridden from outside).
  efs:
    name: crossplane-efs
    network:
      name: crossplane-efs-network
      vpcId:
      cidrIp:
      mounttarget:
        subnets:
          - az:
            scope:
            id:
          - az:
            scope:
            id:
          - az:
            scope:
            id:

provider:
  # provider.awsConfigName -- The name of the AWS Crossplane Provider used to provision this component.
  awsConfigName:
  # provider.k8sConfigName -- The name of the K8S Crossplane Provider used to provision this component.
  k8sConfigName:
