aws:
  # aws.accountId -- ID of the AWS Account this component should be provisioned to.
  accountId:

xrd:
  # xrd.apiGroup -- The name of the API Group this resource should be exposed to.
  apiGroup:
  # xrd.version -- The version of this component (MUST not be overridden from outside).
  version: v1alpha1

composition:
  # composition.name -- The name of the crossplane composition (MUST not be overridden from outside).
  efs:
    name: crossplane-efs
    network:
      name: crossplane-efs-network
      vpcId: vpc-0d4f2f4f6e1fc386c
      cidrIp: 10.19.128.0/18
      mounttarget:
        subnets:
          - az: eu-west-1a
            scope: private
            id: subnet-00a68d9f7c298071c
          - az: eu-west-1b
            scope: private
            id: subnet-0a859aaa7c19e393e
          - az: eu-west-1c
            scope: private
            id: subnet-03a442384bd785047

provider:
  # provider.awsConfigName -- The name of the AWS Crossplane Provider used to provision this component.
  awsConfigName:
  # provider.k8sConfigName -- The name of the K8S Crossplane Provider used to provision this component.
  k8sConfigName:
