apiVersion: v1
description: Helm chart for creating the resources a Tenant needs. For the beginning, this includes only the ArgoCD resources.
name: dvpe-tenant
version: 0.1.0
home: https://github.com/dvpe-cloud/dvpe-helm
