{{- range $_, $tenant := .Values.tenants }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $tenant.name }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tenant.name }}-sa
  namespace: {{ $.Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $tenant.name }}
type: kubernetes.io/service-account-token
---
{{- end }}


