{{- if .Values.netfilter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: update-iptables-script
  namespace: kube-system
data:
  update-iptables.sh: |
    #!/bin/bash
    apk update
    apk add iptables
    {{- range $if := .Values.netfilter.blocked.interfaces }}
    {{- range $ip := $.Values.netfilter.blocked.ipv4 }}
    /sbin/iptables --insert FORWARD 1 --in-interface {{ $if }} --destination {{ $ip }} --jump DROP
    /sbin/iptables -t mangle -A POSTROUTING -o {{ $if }} --destination {{ $ip }} --jump DROP
    {{- end }}
    {{- end }}
{{- end }}
