{{- if .Values.netfilter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: dvpe-netfilter
    dvpe-netfilter-version: {{ .Chart.Version }}
  name: dvpe-netfilter
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: dvpe-netfilter
  template:
    metadata:
      labels:
        k8s-app: dvpe-netfilter
        dvpe-netfilter-version: {{ .Chart.Version }}
    spec:
      initContainers:
      - name: bootstrap
        image: alpine:edge
        command: [ "/bin/sh" ]
        args:
        - -c
        - /scripts/update-iptables.sh
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
          - mountPath: /mnt/host
            name: rootfs
          - name: update-iptables-script
            mountPath: /scripts/update-iptables.sh
            subPath: update-iptables.sh
      hostNetwork: true
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
      volumes:
      - name: rootfs
        hostPath:
          path: /
          type: ""
      - name: update-iptables-script
        configMap:
          name: update-iptables-script
          defaultMode: 0755
{{- end }}