{{- $imageUrl := include "image.url" . -}}
{{- $containerName := include "container.name" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{ .Values.issuercontroller.plane.name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.issuercontroller.namespace }}
spec:
  selector:
    matchLabels:
      control-plane: {{ .Values.issuercontroller.plane.name }}
  template:
    metadata:
      labels:
        control-plane: {{ .Values.issuercontroller.plane.name }}
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: {{ $imageUrl }}
        imagePullPolicy: {{ .Values.issuercontroller.spec.pullPolicy }}
        name: {{ $containerName }}
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: {{ .Values.issuercontroller.externalsecrets.name }}
      restartPolicy: Always