{{- $imageUrl := include "image.url" . -}}
{{- $containerName := include "container.name" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{ .Values.issuercontroller.plane.name }}
  name: {{ .Release.Name }}-issuer-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      control-plane: {{ .Values.issuercontroller.plane.name }}
  template:
    metadata:
      labels:
        control-plane: {{ .Values.issuercontroller.plane.name }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}-sa
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: {{ $imageUrl }}
        imagePullPolicy: {{ .Values.issuercontroller.spec.image.pullPolicy }}
        name: {{ $containerName }}
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 60Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
      - name: docker-reg-secret
      restartPolicy: Always
