{{- with .Values.issuercontroller.externalsecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-reg-secret
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name:  {{ .secretStoreRefName }}
  target:
    template:
      data:
        .dockerconfigjson: "{{ `{{ .dockerRegSecret }}` }}"
      type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
  data:
    - remoteRef:
        key: {{ .dockerCredentials }}
      secretKey: dockerRegSecret

---

{{- end}}
