{{- $namespace := .Release.Namespace }}

{{- with .Values.issuercontroller.externalsecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default .name .dockerCredentials }}
  namespace: {{ $namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store-{{ $namespace }}
  target:
    template:
      type: kubernetes.io/dockerconfigjson
    name: {{ default .name .dockerCredentials }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "{{ default .name .dockerCredentials }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wadtfy-cluster-issuer-secret
  namespace: {{ $namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store-{{ $namespace }}
  target:
    name: {{ .clusterIssuer }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "{{ .clusterIssuer }}"
{{- end}}
