apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.issuercontroller.externalsecrets.name }}
  namespace: {{ .Values.issuercontroller.namespace }}
  labels:
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  dataFrom:
    - {{ .Values.issuercontroller.externalsecrets.name }}