{{- $namespace := .Release.Namespace }}

{{- with .Values.issuercontroller.externalsecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default .name .dockerCredentials }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name:  {{ .secretStoreRefName }}
  target:
    template:
      data:
        .dockerconfigjson: "{{ `{{ .dockerRegSecret }}` }}"
      type: kubernetes.io/dockerconfigjson
    name: {{ default .name .dockerCredentials }}
    creationPolicy: Owner
  data:
    - remoteRef:
        key: {{ default .name .dockerCredentials }}
      secretKey: dockerRegSecret

---

{{- end}}
