apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-container-reg-secret
  namespace: bmw-pki-issuer-system
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: global/github-container-reg-secret
    secretKey: dockerRegSecret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: wadtfy-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-container-reg-secret
    template:
      data:
        .dockerconfigjson: '{{ .dockerRegSecret }}'
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
