{{- $namespace := .Release.Namespace }}

{{- with .Values.issuercontroller.externalsecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ default .name .dockerCredentials }}
  namespace: {{ $namespace }}
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  dataFrom:
    - {{ default .name .dockerCredentials }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: wadtfy-cluster-issuer-secret
  namespace: {{ $namespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .clusterIssuer }}
{{- end}}
