apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.issuercontroller.externalsecrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  dataFrom:
    - {{ .Values.issuercontroller.externalsecrets.name }}
