apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wadtfy-issuer-leader-election-role
  namespace: {{ .Values.issuercontroller.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wadtfy-issuer-cert-manager-controller-approve
rules:
- apiGroups:
  - cert-manager.io
  resourceNames: 
    - issuers.controller-manager.dvpe-cloud.github.io/*
    - clusterissuers.controller-manager.dvpe-cloud.github.io/*
  resources:
  - signers
  verbs:
  - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: wadtfy-issuer-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - controller-manager.dvpe-cloud.github.io
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller-manager.dvpe-cloud.github.io
  resources:
  - issuers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wadtfy-issuer-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wadtfy-issuer-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wadtfy-issuer-leader-election-rolebinding
  namespace: {{ .Values.issuercontroller.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wadtfy-issuer-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.issuercontroller.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wadtfy-issuer-cert-manager-controller-approve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wadtfy-issuer-cert-manager-controller-approve
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: {{ .Values.issuercontroller.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wadtfy-issuer-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wadtfy-issuer-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.issuercontroller.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wadtfy-issuer-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wadtfy-issuer-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.issuercontroller.namespace }}