apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane:  {{ .Values.issuercontroller.plane.name }}
  name: wadtfy-issuer-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  selector:
    control-plane: {{ .Values.issuercontroller.plane.name }}
