argo-cd:
  ## ArgoCD configuration
  ## Ref: https://github.com/argoproj/argo-cd
  ## Ref: https://artifacthub.io/packages/helm/argo/argo-cd/2.11.2

  ## Server
  server:
    # argo-cd.server.extraArgs -- Additional command line arguments to pass to argocd-server
    extraArgs:
      - --insecure # TLS handled by ISTIO (cluster-internally) and Gloo (externally)

    # argo-cd.server.extraArgs -- Argo server log format: text|json
    logFormat: json
    # argo-cd.server.logLevel -- Argo server log level
    logLevel: info

    ## Server service configuration
    service:
      # argo-cd.server.service.servicePortHttp -- Argo server service http port
      servicePortHttp: 80
      # argo-cd.server.service.servicePortHttpName -- Argo server service http port name, can be used to route traffic via istio
      servicePortHttpName: http

    ## ArgoCD config
    ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    config:
      # url: Argo CD's base URL will be set automatically by terraform module.
      # argo-cd.server.config.repositories -- List of config repos, as described in https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#repositories
      repositories:
      # repositories: |
      #   - url: git@github.com:group/repo.git
      #     sshPrivateKeySecret:
      #       name: secret-name
      #       key: sshPrivateKey
      #   - type: helm
      #     url: https://kubernetes-charts.storage.googleapis.com
      #     name: stable
      #   - type: helm
      #     url: https://argoproj.github.io/argo-helm
      #     name: argo

      # argo-cd.server.config.oidc.config -- oidc provider config, as described in https://argoproj.github.io/argo-cd/operator-manual/user-management/#existing-oidc-provider
      oidc.config:
      #   name: WebEAM.Next # e.g. WebEAM.Next-integration
      #   issuer: https://auth.bmwgroup.net:443/auth/oauth2/realms/root/realms/intranetb2x # e.g. https://auth-i.bmwgroup.net:443/auth/oauth2/realms/root/realms/intranetb2x
      #   clientID:
      #   clientSecret:
      #   # Optional set of OIDC scopes to request. If omitted, defaults to: ["openid", "profile", "email", "groups"]
      #   requestedScopes: [ "openid" ]
      #   # Optional CLI Client ID
      #   #cliClientID: ${oidc_client_id_cli}

    # argo-cd.server.configAnnotations -- Annotations to be added to ArgoCD ConfigMap
    configAnnotations: { "helm-chart": "dvpe-helm/dvpe-argocd" }

    ## ArgoCD rbac config
    ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
    rbacConfig:
      # argo-cd.server.policy.csv -- policy.csv is an file containing user-defined RBAC policies and role definitions, as described in https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
      policy.csv:
      # policy.csv: |
      #   # Grant all members of the group '<qnumber>' admin rights
      #   p, my-org:team-alpha, applications, sync, my-project/*, allow
      #   # Grant the user with the q-number q123456 admin privileges (needs oidc configuration)
      #   g, q123456, role:admin
      # argo-cd.server.policy.default -- Name of the default role which Argo CD will falls back to, when authorizing API requests. If omitted or empty, users may be still be able to login, but will see no apps, projects, etc...
      policy.default: role:readonly

    # argo-cd.server.rbacConfigAnnotations -- Annotations to be added to ArgoCD rbac ConfigMap
    rbacConfigAnnotations: { "helm-chart": "dvpe-helm/dvpe-argocd" }

    ## Enable Admin ClusterRole resources.
    clusterAdminAccess:
      # argo-cd.server.clusterAdminAccess.enabled -- Enables an `admin` user outside of OIDC. The initial password is autogenerated to be the pod name of the Argo CD API server.
      enabled: false

  ## Controller
  controller:
    # argo-cd.controller.enableStatefulSet -- Deploy the application as a StatefulSet instead of a Deployment, this is required for HA capability. This is a feature flag that will become the default in chart version 3.x
    enableStatefulSet: true

    ## argo-cd.controller.logFormat -- Argo controller log format: text|json
    logFormat: json

  ## Argo Configs
  configs:
    knownHosts:
      data:
        # argo-cd.configs.knownHosts.data.ssh_known_hosts -- List of known hosts of git repositories. See https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#ssh-known-host-public-keys
        ssh_known_hosts: |
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
          gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
          gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
          ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
          vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
          bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
          [git.bmwgroup.net]:7999,[160.48.66.47]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1mMeortEsruBLnRKltGfQUjA4lghYZWMljdeTdE5Tx86Mrj7WGZVjkNzJYDnoirU8Nb79TbHuYu84mLglqRB/z/2L1K32eCUKR+LipLvqFZvhtTSxlO80UIBBRxyjBwMEpdmfJUqZJCcYw5X+jVADYYfX93/gD92MNzWp6D8tW4fvnWlAaMIKhUxA/k4iXvwA77VpmvIB7Twxt8NHsa4ehER+JzSuZoOIqUARzkhvBuHTRlxTlMuyVGfyOYfixntZ1+BiQsh9r/HxUvAnvwXj5Jb67hPkATKPAibo2tyNCVfoJernlVCrWNEyW1StNboPjxJLeKEzFWbHR6fOa+FB


# -------------------------------------#
# Gloo general value section           #
# -------------------------------------#
gloo:
  # gloo.enabled -- When set to false only the application's deployment resources will be installed with this chart. Can be used to explicitly avoid deploying a VirtualService resource.
  enabled: true
  # gloo.namespace -- `Namespace` where all Gloo resources are deployed.
  namespace: gloo-system

  # -------------------------------------#
  # Gloo VirtualService value section    #
  # -------------------------------------#
  virtualservice:
    # gloo.virtualservice.namespace -- `Namespace` where gloo virtualservice is deployed.
    namespace: gloo-system
    spec:
      sslConfig:
        secretRef:
          # gloo.virtualservice.spec.sslConfig.secretRef.name -- Name of the secret containing the certificate information for this deployment.
          name:
          # gloo.virtualservice.spec.sslConfig.secretRef.namespace -- Namespace where the secret is located. If empty, gloo namespace is used.
          namespace: gloo-system
      virtualHost:
        # gloo.virtualservice.spec.virtualHost.domains -- `DNS domain name` this service will be published to.
        domains:
        routes:
          # gloo.virtualservice.spec.virtualHost.routes.callbackUrlPath -- Path to `callbackUrl` which needs to be registered at the Identity Provider. Pre-defined route in `VirtualService`.
          callbackUrlPath:
          # gloo.virtualservice.spec.virtualHost.routes.appPath -- Path to `appUrl` where the service can be accessed. Pre-defined route in `VirtualService`.
          appPath:
          # gloo.virtualservice.spec.virtualHost.routes.additionalRoutes -- List of route configurations for this `VirtualService`. See [gloo VirtualService Specification](https://docs.solo.io/gloo-edge/latest/introduction/architecture/concepts/#virtual-services) for details
          additionalRoutes:

  # -------------------------------------#
  # Gloo Upstream value section          #
  # -------------------------------------#
  upstream:
    # gloo.upstream.namespace -- `Namespace` where gloo upstream is deployed.
    namespace:
