apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: '{{ .Values.repository }}'
        revision: HEAD
        directories:
          - path: manifests/*/*
  template:
    metadata:
      name: '{{`{{ path.basenameNormalized }}`}}'
    spec:
      project: {{ .Release.Name }}
      source:
        repoURL: '{{ .Values.repository }}'
        targetRevision: HEAD
        path: '{{`{{ path }}`}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-test.yaml
            - values-prod.yaml
      destination:
        name: in-cluster
        namespace: '{{`{{ path[1] }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: dynamodb.aws.crossplane.io
          kind: Table
          jsonPointers:
            - /spec
            - /metadata
