{{- range $_, $repository := .Values.repositories }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "normalizeRepoPath" $repository.url }}
  namespace: {{ $.Release.Namespace }}
spec:
  roles:
    - name: '{{ include "normalizeRepoPath" $repository.url }}'
      policies:
        - 'p, role:{{ include "normalizeRepoPath" $repository.url }}, projects, *, {{ include "normalizeRepoPath" $repository.url }}, allow'
        - 'p, role:{{ include "normalizeRepoPath" $repository.url }}, applications, *, {{ include "normalizeRepoPath" $repository.url }}/*, allow'
        - 'p, role:{{ include "normalizeRepoPath" $repository.url }}, repositories, *, {{ include "normalizeRepoPath" $repository.url }}, allow'
        {{- range $user := $repository.users }}
        - 'g, {{ $user }}, role:{{ include "normalizeRepoPath" $repository.url }}'
        {{- end }}
{{- end }}
