{{- range $_, $tenant := .Values.tenants }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $tenant.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  sourceRepos:
    - '{{ $tenant.repoURL }}'
  destinations:
    {{- range $namespace := $tenant.namespaces }}
    - namespace: '{{ $namespace }}'
      server: 'https://kubernetes.default.svc'
    {{- end }}
    - namespace: gloo-system
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist: {{- $tenant.clusterResourceWhiteList | toYaml | nindent 4 }}
  roles:
    - name: '{{ $tenant.name }}'
      policies:
        - 'p, role:{{ $tenant.name }}, projects, *, {{ $tenant.name }}, allow'
        - 'p, role:{{ $tenant.name }}, applications, *, {{ $tenant.name }}/*, allow'
        - 'p, role:{{ $tenant.name }}, repositories, *, {{ $tenant.repoURL }}, allow'
        {{- range $user := $tenant.users }}
        - 'g, {{ $user }}, role:{{ $tenant.name }}'
        {{- end }}
{{- end }}
