{{- range $_, $repository := .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{ include "normalizeRepoPath" $repository.url }}-repo
  namespace: {{ $.Release.Namespace }}
stringData:
  type: 'git'
  url: '{{ $repository.url }}'
  githubAppInstallationID: '{{ $repository.githubAppInstallationId }}'
{{- end }}
