apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{ .Release.Name }}-repo
  namespace: {{ .Release.Namespace }}
stringData:
  type: 'git'
  url: '{{ .Values.repository }}'
  githubAppInstallationID: '{{ .Values.githubAppInstallationId }}'
