clcm:
  # clcm.host -- CLCM host
  host:
  # clcm.port -- CLCM port
  port:
  # clcm.healthCheckTimeoutInSeconds -- CLCM health check interval in seconds
  healthCheckTimeoutInSeconds: 60
# internet -- configuration for the internet cluster issuer
internet:
  # -- CA instance
  caInstance:
  # -- CA type
  certificateDateCAType:
  # -- CI id
  ciID:
  # -- CI type
  ciType:
  # -- CI client
  ciClient:
  # -- CI contact e-mail
  ciContactEmail:
  # -- CI requester
  ciRequester:
# intranet -- configuration for the intranet cluster issuer
intranet:
  # -- CA instance
  caInstance:
  # -- CA type
  certificateDateCAType:
  # -- CI id
  ciID:
  # -- CI type
  ciType:
  # -- CI client
  ciClient:
  # -- CI contact e-mail
  ciContactEmail:
  # -- CI requester
  ciRequester:
