name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/ct.yaml
  helm-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run helm-docs
        run: .github/helm-docs.sh
  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - helm-docs
    strategy:
      matrix:
        k8s:
          - v1.19.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
